#!/bin/bash
# Aplications : gmd5
# Copyright   : GNU GPLv3 
# Author      : Dindin Hernawan <dindin_hernawan@yahoo.com>

# Mengecek lokasi
cd $(pwd)
# Perintah Find bisa di cek dan di pahami di https://linux.die.net/man/1/find
find -type f -exec md5sum "{}" + > md5sums
#      type f (regular file )   > cetak 
echo 'Sukses'
# Menampilkan Sukses
